import { StyleSheet } from "react-native";


export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#4f6d7a",
      justifyContent: "top",
      alignItems: "center",
      width:"100%"
    },
    card: {
      backgroundColor: "#e8dab2",
      borderRadius: 10,
      padding: 20,
      marginTop: 20,
      alignItems: "center",
      shadowColor: "black",
      elevation: 10,
      width:"90%"
    },
    textInput: {
      color: "black",
      backgroundColor: "white",
      borderRadius: 10,
      padding: 10,
      width: "70%",
      shadowColor: "black",
      shadowOpacity: 1,
      shadowRadius: 10,
      elevation: 5,
    },
    button: {
      fontSize: 20,
      color: "white",
      backgroundColor: "#c0d6df",
      borderRadius: 10,
      padding: 5,
      margin: 5,
      width: 100,
      alignItems: "center",
      shadowColor: "black",
      shadowOpacity: 1,
      shadowRadius: 7,
      elevation: 5,
    },
    addButton: {
      fontSize: 20,
      color: "white",
      backgroundColor: "#c0d6df",
      borderRadius: 10,
      padding: 5,
      margin: 5,
      width: 30,
      alignItems: "center",
      shadowColor: "black",
      shadowOpacity: 1,
      shadowRadius: 7,
      elevation: 5,
    },
    button2: {
      fontSize: 20,
      color: "white",
      backgroundColor: "white",
      borderRadius: 10,
      padding: 5,
      margin: 5,
      alignItems: "center",
      shadowColor: "black",
      shadowOpacity: 1,
      shadowRadius: 7,
      elevation: 5,
    },
    saveButton: {
      fontSize: 20,
      color: "white",
      backgroundColor: "#449342",
      color: "white",
      borderRadius: 10,
      padding: 5,
      margin: 5,
      width: 190,
      alignItems: "center",
      shadowColor: "black",
      shadowOpacity: 1,
      shadowRadius: 7,
      elevation: 5,
    },
    deleteButton: {
      fontSize: 20,
      color: "white",
      backgroundColor: "#ff0000",
      color: "white",
      borderRadius: 10,
      padding: 5,
      margin: 5,
      width: 190,
      alignItems: "center",
      shadowColor: "black",
      shadowOpacity: 1,
      shadowRadius: 7,
      elevation: 5,
    },
    buttonContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
    },
    flatList: {
      marginTop: 20,
      color: "white",
    },
    text: {
      fontSize: 20,
      color: "black",
    },
    title: {
      fontSize: 20,
      color: "black",
    },
    editableTitle: {
      fontSize: 20,
      color: "black",
      borderRadius: 10,
      padding: 10,
    },
    map: {
      width: "100%",
      height: "100%",
    },
    overlay: {
      position: "absolute",
      left: 20,
      right: 20,
      top: 20,
      backgroundColor: "white",
      padding: 5,
      borderRadius: 10,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      elevation: 50,
    },
  
    overlayTitle: {
      fontSize: 16,
      fontWeight: "bold",
      textAlign: "center",
    },
    overlayImage: {
      width: "100%",
      height: 200, // Adjust as needed
      marginTop: 10,
    },
    markerStyle: {
      width: 30, // Regular marker size
      height: 30,
      backgroundColor: "black",
      borderRadius: 15,
      alignItems: "center",
      justifyContent: "center",
    },
    selectedMarkerStyle: {
      width: 30, // Larger size for selected marker
      height: 30,
      backgroundColor: "red",
      borderRadius: 15,
    },
  });
  